# -*- coding: utf-8 -*-
"""
/***************************************************************************
 LandfireLoader
                                 A QGIS plugin
 Loads landfire and spp. richness data
 Generated by Plugin Builder: http://g-sherman.github.io/Qgis-Plugin-Builder/
                             -------------------
        begin                : 2024-12-22
        copyright            : (C) 2024 by 3point.xyz
        email                : vance@3point.xyz
        git sha              : $Format:%H$
 ***************************************************************************/

/***************************************************************************
 *                                                                         *
 *   This program is free software; you can redistribute it and/or modify  *
 *   it under the terms of the GNU General Public License as published by  *
 *   the Free Software Foundation; either version 2 of the License, or     *
 *   (at your option) any later version.                                   *
 *                                                                         *
 ***************************************************************************/
 This script initializes the plugin, making it known to QGIS.
"""


# noinspection PyPep8Naming
def classFactory(iface):  # pylint: disable=invalid-name
    """Load LandfireLoader class from file LandfireLoader.

    :param iface: A QGIS interface instance.
    :type iface: QgsInterface
    """
    #
    from .Loader import LandfireLoader
    return LandfireLoader(iface)
